DELETE http://localhost:3003/api/blogs/62ff9604743057b0b76668c3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhYmFiYWJhIiwiaWQiOiI2MmZmN2I4MmQ5MzBmMzA2ODBkMjE5YTkiLCJpYXQiOjE2NjExNzczNTJ9.CCN822FT_OnxewX1piFT57F3TlhvAf55SVprtK_Nhuo